export enum ErrorType {
    INVALID_KEY = "invalid_key",
    INVALID_LICENCE = "invalid_licence",
    INVALID_LICENCE_TYPE = "invalid_licence_type",
    LICENSE_EXPIRED = "license_expired",
    INVALID_LICENCE_CREATED_AT = "invalid_licence_created_at",
    WEBSITE_NOT_FOUND = "website_not_found",
    WEBSITE_NOT_FOUND_BY_LICENCE = "website_not_found_by_licence",
    USER_NOT_FOUND = "user_not_found",
    UNAUTHORIZED = "unauthorized",
    INVALID_PASSWORD = "invalid_password",
    USER_ALREADY_EXISTS = "user_already_exists",
    INTERNAL_SERVER_ERROR = "internal_server_error",
    WEBHOOK_URL_INVALID = "webhook_url_invalid",
    ROLE_NOT_FOUND = "role_not_found",
    ROLE_NOT_MODIFIABLE = "role_not_modifiable",
    ROLE_ALREADY_EXISTS = "role_already_exists",
    ROLE_UPDATE_FAILED = "role_update_failed",
    SERVER_NOT_FOUND = "server_not_found",
    SERVER_UPDATE_FAILED = "server_update_failed",
    SERVER_CONNECTION_FAILED = "server_connection_failed",
    PRODUCT_NOT_FOUND = "product_not_found",
    PRODUCT_UPDATE_FAILED = "product_update_failed",
    PRODUCT_DELETE_FAILED = "product_delete_failed",
    CATEGORY_NOT_FOUND = "category_not_found",
    CATEGORY_UPDATE_FAILED = "category_update_failed",
    CATEGORY_DELETE_FAILED = "category_delete_failed",
    CATEGORY_HAS_PRODUCTS = "category_has_products",
    ROLE_HAS_USERS = "role_has_users",
    SERVER_HAS_PRODUCTS = "server_has_products",
    INVALID_REFRESH_TOKEN = "invalid_refresh_token",
    INVALID_ACCESS_TOKEN = "invalid_access_token",
    INSUFFICIENT_BALANCE = "insufficient_balance",
    CHEST_ITEM_NOT_FOUND = "chest_item_not_found",
    CHEST_ITEM_ALREADY_USED = "chest_item_already_used"
}

export const ErrorMessages = {
    [ErrorType.INVALID_KEY]: "Geçersiz lisans anahtarı",
    [ErrorType.INVALID_LICENCE]: "Geçersiz lisans",
    [ErrorType.INVALID_LICENCE_TYPE]: "Geçersiz lisans türü",
    [ErrorType.LICENSE_EXPIRED]: "Lisans süresi doldu",
    [ErrorType.INVALID_LICENCE_CREATED_AT]: "Geçersiz lisans oluşturma tarihi",
    [ErrorType.WEBSITE_NOT_FOUND]: "Website bulunamadı",
    [ErrorType.WEBSITE_NOT_FOUND_BY_LICENCE]: "Website bulunamadı lisans ile",
    [ErrorType.USER_NOT_FOUND]: "Kullanıcı bulunamadı",
    [ErrorType.UNAUTHORIZED]: "Yetkisiz",
    [ErrorType.INVALID_PASSWORD]: "Geçersiz şifre",
    [ErrorType.USER_ALREADY_EXISTS]: "Kullanıcı zaten mevcut",
    [ErrorType.INTERNAL_SERVER_ERROR]: "İç sunucu hatası",
    [ErrorType.WEBHOOK_URL_INVALID]: "Webhook URL geçersiz",
    [ErrorType.ROLE_NOT_FOUND]: "Rol bulunamadı",
    [ErrorType.ROLE_NOT_MODIFIABLE]: "Rol değiştirilemez",
    [ErrorType.ROLE_ALREADY_EXISTS]: "Rol zaten mevcut",
    [ErrorType.ROLE_UPDATE_FAILED]: "Rol güncellenemedi",
    [ErrorType.SERVER_NOT_FOUND]: "Sunucu bulunamadı",
    [ErrorType.SERVER_UPDATE_FAILED]: "Sunucu güncellenemedi",
    [ErrorType.SERVER_CONNECTION_FAILED]: "Sunucu bağlantısı kurulamadı",
    [ErrorType.PRODUCT_NOT_FOUND]: "Ürün bulunamadı",
    [ErrorType.PRODUCT_UPDATE_FAILED]: "Ürün güncellenemedi",
    [ErrorType.PRODUCT_DELETE_FAILED]: "Ürün silinemedi",
    [ErrorType.CATEGORY_NOT_FOUND]: "Kategori bulunamadı",
    [ErrorType.CATEGORY_UPDATE_FAILED]: "Kategori güncellenemedi",
    [ErrorType.CATEGORY_DELETE_FAILED]: "Kategori silinemedi",
    [ErrorType.CATEGORY_HAS_PRODUCTS]: "Kategori ürünleri var",
    [ErrorType.ROLE_HAS_USERS]: "Rol kullanıcıları var",
    [ErrorType.SERVER_HAS_PRODUCTS]: "Sunucu ürünleri var",
    [ErrorType.INVALID_REFRESH_TOKEN]: "Geçersiz yenileme tokeni",
    [ErrorType.INVALID_ACCESS_TOKEN]: "Geçersiz erişim tokeni",
    [ErrorType.INSUFFICIENT_BALANCE]: "Yetersiz bakiye",
    [ErrorType.CHEST_ITEM_NOT_FOUND]: "Chest item bulunamadı",
    [ErrorType.CHEST_ITEM_ALREADY_USED]: "Chest item zaten kullanıldı"
}
