export enum PERMISSIONS {
    MANAGE_USERS = "manage_users",
    MANAGE_ROLES = "manage_roles",
    MANAGE_PERMISSIONS = "manage_permissions",
    MANAGE_SETTINGS = "manage_settings",
    MANAGE_LOGS = "manage_logs",
    MANAGE_NOTIFICATIONS = "manage_notifications",
    MANAGE_SERVERS = "manage_servers",
    MANAGE_TICKETS = "manage_tickets",
    MANAGE_BANS = "manage_bans",
    MANAGE_WEBHOOKS = "manage_webhooks",
    MANAGE_ADMINS = "manage_admins",
    MANAGE_MODERATORS = "manage_moderators",
    MANAGE_BOTS = "manage_bots",
    MANAGE_SERVER_SETTINGS = "manage_server_settings",
    MANAGE_SERVER_ROLES = "manage_server_roles",
    MANAGE_SERVER_PERMISSIONS = "manage_server_permissions",
    MANAGE_CATEGORIES = "manage_categories",
    MANAGE_PAYMENTS = "manage_payments",
    MANAGE_PRODUCTS = "manage_products",
    WEBSITE_OWNER = "website_owner",
    MANAGE_WEBSITE = "manage_website",
    MANAGE_SLIDERS = "manage_sliders",
}